spring:
  datasource:
    url: jdbc:mysql://localhost:3306/brushtopicya
    username: root
    password: yzc13569291231
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    time-zone: Asia/Shanghai


server:
  servlet:
    context-path: /brushTopicYa

    encoding:
      force: true
      charset: UTF-8

  port: 8848